### ISSUE TITLE
We need to add translation to spanish

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/git-interactive-tutorial#1]
The tutorial is ready in spanish you can take it here on the live link: https://4GeeksAcademy.github.io/git-interactive-tutorial

The entire translation is inside the `src/config/config.json` folder [here](https://github.com/4GeeksAcademy/git-interactive-tutorial/blob/master/src/config/config.json).

To translate to english you have to modify the json section inside `json.lecciones.en` here:

```json
{
    "lecciones": {
        "es": {
        },
        "en": {
               HERE is where the translation must be made
        }
}
```

**Comment by insomnux** [comment]
I can work on this, though I am not a native speaker.

**Comment by alesanchezr** [comment]
Hey @insomnux if you want to give it a try go ahead. We will add you in the contributors section that we are building on the README.md

**Comment by alesanchezr** [comment]
Hey @insomnux I have merged and publish your first 10 translated lessons already, everything is working fine 😄

**Comment by insomnux** [comment]
Awesome, will work on the rest :smiley:

**Comment by alesanchezr** [comment]
thank you for your contribution @aliciaphes u will be added to the contributors list.

We are missing only a few translation strings!
